### PR TITLE
Changing Dependency Package

### PR DESCRIPTION
**Pull request by vgokulakannan**

### CODE REVIEW

**Comment by thomasconner** [comment]
`kinvey-angular` is deprecated in favor of `kinvey-angular-sdk`. Can you please make this change?

**Comment by vgokulakannan** [comment]
Hi Thomas, as you said changed the package to "kinvey-angular-sdk"(version:1.6.6).  But the app is not working properly.

It works only  with the package "kinvey-angular"(version:2.0.0)

**Comment by thomasconner** [comment]
Ok I will take a look at it.

**Comment by thomasconner** [comment]
I just updated the app and it's dependencies. I am closing the pull request but if you find something else wrong that needs to be fixed, submit a new PR and I will take a look. Thanks for helping out!

**Pull request closed without merging**
